# Generated by Django 4.2.30 on 2026-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_token", models.CharField(blank=True, max_length=120)),
                ("chat_id", models.CharField(blank=True, max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("violation_threshold", models.PositiveIntegerField(default=1)),
                ("cooldown_minutes", models.PositiveIntegerField(default=5)),
                ("last_alert_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_violations", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Alert Settings",
            },
        ),
    ]
